---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.deployment.name }}
  labels:
    app: pyapp
spec:
  replicas: {{ .Values.app.deployment.replicas }}
  selector:
    matchLabels:
      app: pyapp
  template:
    metadata:
      labels:
        app: pyapp
    spec:
      containers:
        - name: pyapp
          image: {{ .Values.app.deployment.image }}
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: {{ .Values.app.deployment.secretRefName }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.service.name }}
  labels:
    app: pyapp
spec:
  type: {{ .Values.app.service.type }}
  selector:
    app: pyapp
  ports:
    - protocol: TCP
      port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.service.targetPort }}

