apiVersion: v1
kind: Pod
metadata:
  name: mongo-shell
  namespace: default
spec:
  containers:
  - name: mongo-shell
    image: mongo:4.4
    command: ["bash"]
    stdin: true
    tty: true
  restartPolicy: Never
